#!/bin/sh

#todo #fixme - find a way to avoid duplicating this logic at the top
#              currently it's in both sqlite-diff and sqlite-merge
isDarwin() {
    [ "$(uname)" == "Darwin" ]
}
# Mac OS X has different readlink behavior, so use GNU coreutils greadlink
if isDarwin; then
    readlinkCmd=greadlink
else
    readlinkCmd=readlink
fi
trunk="$(dirname "$($readlinkCmd -f $0)")"

. $trunk/util.sh

ancestor="$1"
local="$2"
remote="$3"
marker="$4"
placeholder="$5"

#ancestor2localDiff=$(diffDb "$ancestor" "$local")
ancestor2remoteDiff=$(diffDb "$ancestor" "$remote")
printErr $ancestor2remoteDiff
sqlite3 "$local" "$ancestor2remoteDiff"
#echo "marker='$marker'"
#echo "placeholder='$placeholder'"
#exit 1
