#!/bin/sh
trunk="$(dirname "$(readlink -f $0)")"

. $trunk/util.sh

ancestor="$1"
local="$2"
remote="$3"
marker="$4"
placeholder="$5"

#ancestor2localDiff=$(diffDb "$ancestor" "$local")
ancestor2remoteDiff=$(diffDb "$ancestor" "$remote")
printErr $ancestor2remoteDiff
sqlite3 "$local" "$ancestor2remoteDiff"
#echo "marker='$marker'"
#echo "placeholder='$placeholder'"
#exit 1
